server:
  port: 8093
  servlet:
    session:
      timeout: 1h

spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cuhelperdb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: cuhelperuser
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  pagination:
    write_pages: 10
    page_rows: 10

  upload:
    path: /opt/uploads/worksheets
